form/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^form_app/',include('form_app.urls'))
]

form_app/urls.py
from django.conf.urls import url
 
from form_app import views
 
app_name = 'form_app'
 
urlpatterns = [
 
    # /modelforms/
    url(r'^$', views.IndexView.as_view(), name='index'),
 
    # modelforms/product/entry
    url(r'^user_details/entry/$',views.User_detailsEntry.as_view(),name='user-entry'),
 
    # modelforms/product/2
    url(r'^user_details/(?P<pk>[0-9]+)/$', views.User_detailsUpdate.as_view(), name='user-update'),
 
    # modelforms/product/(?P<pk>[0-9]+)/delete
    url(r'^users/(?P<pk>[0-9]+)/delete$', views.User_detailsDelete.as_view(), name='user-delete'),
 
]

form_app/models.py
from django.db import models
from django.urls import reverse


class User_details(models.Model):
 
    user_name = models.CharField(max_length=100)
    mobile    = models.CharField(max_length=10)
    location  = models.CharField(max_length=100)
    address   = models.TextField()
    
    def get_absolute_url(self):
        return reverse('form_app:index')
        
    class Meta:
        db_table = 'user_details'

form_app/views.py
from django.shortcuts import render

from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
 

from .models import User_details
 
class IndexView(generic.ListView):
    context_object_name = 'User_details_list'
    template_name = 'form_app/index.html'
 
    def get_queryset(self):
        return User_details.objects.all()
 

class User_detailsEntry(CreateView):
    model = User_details
    fields = ['user_name', 'mobile', 'location', 'address']
 

class User_detailsUpdate(UpdateView):
    model = User_details
    fields = ['user_name', 'mobile', 'location', 'address']
    
    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        slug = self.kwargs.get(self.slug_url_kwarg, None)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        # Next, try looking up by slug.
        elif slug is not None:
            slug_field = self.get_slug_field()
            queryset = queryset.filter(**{slug_field: slug})
        # If none of those are defined, it's an error.
        else:
            raise AttributeError("Generic detail view %s must be called with "
                                 "either an object pk or a slug."
                                 % self.__class__.__name__)
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except ObjectDoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj
 

class User_detailsDelete(DeleteView):
    model = User_details
    success_url = reverse_lazy('form_app:index')

form_app/templates/form_app/form-template.html
{% for field in form %}
    <div class="form-group">
        <div >
            <span class="text-danger la">{{ field.errors }}</span>
        </div>
        <label  >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

form_app/templates/form_app/index.html
{% if User_details_list %}
 
    {% for user in User_details_list %}
 
    <ul>
 
    <li>
        <h2> User Name:{{ user.user_name }}</h2>
        <h2> Mobile:{{ user.mobile }}</h2>
        <h2>Location:{{ user.location }} </h2>
           <form action="{% url 'form_app:user-delete' user.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Delete</button>
        </form>
           <form action="{% url 'form_app:user-update' user.id  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Update</button>
        </form>
 
 
    </li>
 
 
    </ul>
 
{% endfor %}
 
    {% else %}
    <h1>No User Details found on the database.</h1>
 
 
{% endif %}
     <form action="{% url 'form_app:user-entry'  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Make a User entry here</button>
        </form>

form_app/templates/form_app/user_details_form.html
<h3>Add New User</h3>
 
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'form_app/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>